name: CI-CD with KinD

on:
  push:
    branches: [ dev, stage, prod ]

jobs:
  deploy:
    runs-on: [self-hosted, agent-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t landing-page:${{ github.ref_name }} .

      - name: Load image into KinD
        run: |
          kind load docker-image landing-page:${{ github.ref_name }} --name cicd-cluster

      - name: Deploy to Kubernetes
        run: |
          kubectl create namespace ${{ github.ref_name }} || true

          sed "s/IMAGE_TAG/${{ github.ref_name }}/g" k8s/deployment.yaml \
          | kubectl apply -n ${{ github.ref_name }} -f -

          kubectl apply -n ${{ github.ref_name }} -f k8s/service.yaml
